* Primo
(mancato)

* Secondo
(mancato)

* Terzo
presente
** Formula di Clos
si riparte in bellezza
serve a trovare i valori ottimi per lo stadio intermedio per una struttura a tre stadi affinchè resti non bloccante minimizzando comunque il costo

*** Dati / ipotesi
ci mettiamo nel caso peggiore possibile
le ipotesi, se non si fa queste ipotesi non si arriva al caso peggiore
 - in cui vogliamo collegare l'unica linea libera in entrata all'unica linea libera in uscita
 - le occupate in entrata sono disgiunte dalle occupate in uscita
 - le occupaggini dal primo al secondo livello sono disgiunte dalle occupaggini dal terzo al secondo livello

detto questo

** Il bridge, cos'è, che fa
il bridge è un dispositivo fisico che connette più reti lan
questa è una cosa positiva perchè vogliamo connettere più reti lan minimizzando le collisioni

il bridge segue una tecnica di autoapprendimento per capire ...
flooding ...
e poi con il messaggio di riscontro capisce a quale dispositivo era...

ok ma così il bridge non farebbe niente, il bridge in realtà fa qualcosa, cioè filtra
il bridge è un dispositivo /plug and play/ cioè lo metti lì e non devi configurare niente

in maniera indiretta, quando arriva il pacchetto, legge l'indirizzo sorgente e la porta sorgente e boh
(molto detto dal fantacci)

** Routing Multicast e Multi Unicast
 - Multicast :: 
 - Multi Unicast ::
uno manda a molti, manda più copie dello stesso messaggio che però non vengono tutte recapitate a...

*** Differenza pratica
quella è la differenza funzionale tra i due metodi
qual'è la differenza pratica tra i due metodi?

il multi unicast è più congestionato

voto: 26

* Quarto
ingegneria informatica
** Formula di Lee
la formula di lee serve invece
viene studiata perchè a volte la condizione di non blocco non serve
spesso le reti non sono utilizzate per tutta la loro capacità, a volte basta che la probabilità che il commutatore vada in blocco sia molto bassa

dato una \(\alpha\), probabilità che una trama sia bloccata, allora \(p = \alpha \times \dots\) 
sono \(N\) linee e \(\frac{N}{n}\) quindi \(p = \alpha \frac{N}{n}\)

non va bene la formula
si provano varie permutazioni di simboli

*** Formula
\(\alpha\) è la probabilità che una linea di ingresso sia occupata
ci sono \(n\) blocchi, quindi \(\frac{N}{n}\) linee di ingresso a blocco, \(k\) linee di uscita a blocco

... dualità di avere una linea di ingresso occupato per via di un'uscita occupata
non ci ho capito un cazzo, la probabilità di blocco
\[ p = \frac{\alpha n}{k} \]

quindi la probabilità di non blocco \(p_n = 1 - p\)
altre cose che mi sono perso
\[ {(1 - {(1 - p)}^2)}^k \]

si nota che è un'approssimazione perchè clos

** DHCP
protocollo con cui vengono assegnati gli IP dinamici
il dispositivo manda un messaggio in broadcast in cui chiede un ip
i server che lo cagano gli mandano, sempre in broadcast, riconosce le richieste con il proprio numero, sceglie un ip, manda un messaggio al server chiedendo se quell'ip dinamico è ancora valido, e il server gli manda un messaggio confermando che è ancora libero sigillando l'accordo per l'assegnazoine dell'ip

** DQDB
reti per le vie metropolitane

ci sono due tipi di slot sui canali, la trama è fatta a slot
i messaggi sono di tipi
 - prenotazoine
 - dati

i dispositivi hanno tre componenti
 - buffer per dati
 - contatore add drop
 - contatore solo drop

quello solo drop conta le ... nel bus opposto... aumenta quando legge una prentoazoine sul campo opposto e diminiuisce ogni volta che legge uno slot col campo di dati vuoto
(fa schema architetturale)

 - c'è l'add drop che legge da tot a incremento e da tat a decremento
 - quando legge ... il valore dell'add drop viene copiato sul contatore drop, per vedere quante trame deve lasciare vuote per vedere quante trame deve lasciare libere prima di mandare il proprio messaggio
 - durante l'attesa del contatore drop il contatore add drop continua ad andare su e giù per mantenere le invarianti che fanno funzionare la rete

28

* Quinto
ingengeira informatica
** Tecnica aloha
è una tecnica dove si manda senza cagare che il canale sia occupato o meno
ci sono due tipi
 - puro
 - slotted

mandi e ascolti sul canale di riscontro
se non trovi il riscontro vuol dire che non ti ha cagato

*** Perchè lo slotted è meglio
l'aloha slotted cos'è che evita che succeda, che può succedere nell'aloha normale
che se te stai trasmettendo e non hai avuto collisione, nessuno può romperti il cazzo durante il tempo di accesso

*** Risoluzoine delle collisioni
scegli un tempo di ritardo massimo e scegli un tempo alla cazzo, con distribuzione uniforme per massimizzare la cazzo, e mandi dopo quel tempo mandi
per quello slotted uguale

** Direct diffusion
per le reti di sensori
quando si è interessati a un'informazione si manda in flooding che voglio l'informazione

per il gradiente si ... da ogni sorgente a ... per definire la qualità del collegamento
viene scelto quello con il graidente più alto che invia

e poi fase di reinforcement da parte del ... per da parte della sorgente che chiede al sink di ignorare eventuali altri ...

** Conteggio all'infinito
(parla molto in fretta)
il conteggio all'infinito si verificha quando hai tre nodi collegati in cascata e uno di questi si guasta e ...

*** Rimedi al problema
 - infinito finito :: hai uan soglia massima di distanza dopo la quale vaffanculo
 - split horizon :: non mandare aggiornamenti a nodi che sono direttamente collegati, ma a volte ...
   - connect reverse :: che serve a fare il refresh del collegamento e ...

voto 28
* Sesto
** FDDI
a doppio anello così se c'è un guasto all'anello superiore può lavorare l'anello inferiore
altrimenti l'anello inferiore può servire ad aumentare la banda e le prestazioni della rete

abemus token target rotatio time, che è quanto ci mettono tutti i nodi a mandare le token
quello per la roba sincrona
\[ TTRT = \sum_{i = vaffa}^{nculo} \alpha _i \]

il token rotation time è il valore...

** Tecnica ??S
qualcosa con lunghezza ... di 32 byte che si basa su principi differenti rispetto al routing normale infatti gestisce informazioni su basi ... rispetto al ...
/flusso/
flussi diversi che hanno la stessa destinazione possono essere mandati su percorsi differenti
una parte di questo N??S è ... su cui vengono instradate ...

** Meccanismo Sliding Windows
e dello slow start

lo sliding windows serve per reagire alla congestione del flusso, consiste in una finestra di lughezza definita che definisce i pacchetti che devono essere inviati a partire dal primo tutti, è un sistema affidabile in quanto prevede il riscontro

*** Slow Start
all'inizio la sliding window è di lughezza minima pari ad 1, non appena il messaggio di arrivo... la sliding window viene aumentata di 1, questo ogni volta che ... avvenuta ricezione, se ciò non accade la lunghezza viene dimezzata o boh

chiusura della finestra si aspetta che tutti i pacchetti vengano trasmessi e non ne ho idea

28

* Settimo
ingengieria informatica
** Nat
network address translation
traduzione di molti ip privati in pochi ip pubblici

permette la traduzione di più ip privati a un solo ip pubblici
 - statico ::
 - dinamico :: un solo ip pubblico
 - boh ::

*** Cosa si intende quando questo sistema ci pone davanti a un'ambigiutà
non si ha più la divisione dei protocolli, tipo quello che fa il routing a livello trasporto  

chiedeva quando due indirizzi della rete nat comunicano con uno stesso indirizzo pubblico
ambiguità perchè (ok non l'ha detto)
abè su usano le porte

si crea una tabella di istradamento che associa a un ip interno e lo associa a un ip fittizio interno
è in questo caso che fa un routing a livello di trasporto, c'è mi vai a invadere il tcp per il routing, povero tcp

il routing lo fa a livello tcp, a livello 4, utilizzando il livello di porta, che è di un livello superiore

** SDN
Software Defined Network
si ottiene tramite la creazione di una rete virtuale la proprietà di gestire tutta la rete da un unico punto di controllo
(bla bla routing generalizzato perchè usa informazioni da più livello)

*** Qual'è la caratteristica saliente di questo tipo di rete
molto più facile da gestire, maggiore sicurezza
prevede la separazione del livello fisico dal livello software

prevede la distinzione dello stato fisico dallo strato di gestione

*** Per mettere più reti su uno stesso hardware
viene adoperata una metodolgia di virtualizzazione, hai più macchine virtuali ognuna delle quali gestisce una rete (perchè avere più processi diversi per reti diverse è troppo mainstream, famo le macchine virtuali va, lo mettiamo anche su aws?)

** Architettura IOT
internet of things
...[fn::mi sono perso questa parte per insultare le macchine virutali]
/SENSING/

26

* Ottavo
(mancato)

* Nono
ingengneria elettronica
ho chiesto tutto ormai c'è poco da fare, si rifa domande
** Parlami della frammentazione
la frammentazione è un concetto che si applica quando ci troviamo a inoltrare un datagramma che eccede le dimensioni massime consentite
... =MDU= o =Maximum Designation Unit=, ... questa operazione per quanto riguarda l'indirizzamento ipv4 è ... dal primo router in uscita e ...

il router a cui è connesso il dispositivo sorgente si occuperà di dividere in più parti il datagramma a seconda dell'mdu e il router ... si occuperà di ricostruire il datagramma
ricollegandoci al fatto che questo è per l'ipv4 ci sono campio specifici nella testata ...

nell'informazine scritta nella testata il campo ... offset a che serve? Come viene utilizzato dai dispositivi
si prevede l'uso di certi campi, uno di questi è il fragment offset, utilizzato nell'ipv4 per la ... della frammentazione, utilizzato per effettuare una corretta ricostruizione del datagramma origianle per

** Tecniche polling
ci sono tecniche mac ordinate e non ordinate, quelle polling sono tra quelle ordinate
le tecniche ordinate provano a evitare puttanaio
il livello mac si occupa di gestire l'accesso ai dispositivo

ritornando alla domanda le tecniche polling prevedono l'invio di un messaggio di autorizzazione da parte di un dispositivo master, ce ne sono due varianti
 - roll call
 - hub polling

*** Roll Call
per architetture più centrali tipo quella a stella, il master invia un messaggio di autorizzazoine a ogni ... che poi lo rimanda al master ...

*** Hub Polling
si adatta ad architetture a bus, il master manda il token all'ultimo nel bus ...

*** Tipi di accesso
 - gated :: utilizzo del canale con un certo tempo massimo predefinito
 - esaustiva :: accesso al canale fino a che non si esaruiscono i dati da mandare

**** il tempo di accesso per la gated
non è uguale per tutti i nodi ma viene determinato in base al numero di pacchetti che arrivano tra un arrivo del token e il successivo

** Sliding window
#+begin_quote
una volta concluso lo slow start
#+end_quote
... la dimesione della finestra è a metà del valore che ha creato la congestione, ... quando viene rilevata la congestione si arriva a un decremento esponenziale della finestra

nella congestion avoidance si ha un incremento lineare e un decremento esponenziale

... permette di distinguere i tipi di congestione, leggera e pesante
 - la congestione è pesante si trova quando non arriva un riscontro in ritardo o quando arrivano tre o più riscontri fuori ordine
 - la congestione leggera, quindi temporanea, è quando si riceve il riscontro di un solo pacchetto... in tal caso si torna alla congestoin avoidance

30, e parecchio meritato cazzo   

* Decimo
#+begin_quote
se poi non te lo verbalizzano non sono cazzi mia
 ~ Il Sommo
#+end_quote
sempre di informatica
** Parlami del conteggio all'infinito
è una problematca che possiamo riscontrare quando l'inoltro dei pacchetti va molto lento,
non siamo arrivati neache all'introduzoine

(silezio cosmico interrotto da rumori di notifiche del Fantacci)

si usa col distance vector
(continua a parlare di riscontri e collisioni, il fantacci non approva)

quando si stanno facendo le tabelle di routing e distance vector
*** Soluzioni
si può avere un valore, tipi 15, per cui superato questo valore

** Parlami del problema del terminale nascosto
(a sto punto questo è un classico)
(silenzio)

possiamo utilizzare ad esempio una procedura di handshake
come si chiamano i messaggi inviati per...

come si chiamano questi messaggi?
 - RTS :: Request to send
 - CTS :: Clear to send

nei cosi che senso ha il campo NAV?

** Tecnica SPIN
la tecnica spin è una tecnica che si usa nelle reti di sensori e utilizza il principio dell'offerta ?
si manda in flooding una domanda di ...

definisci un po' meglio le fasi
 1. nodo pubblica "hey ho un risultato tipo!"
 2. i nodi ... gli dicono se sono interessati
 3. ...
